### ISSUE TITLE
can't find the product named XC7K100T where...

### ISSUE THREAD

**Issue by jihoon-you** [antmicro/data-center-dram-tester#1]
i try to make the dram tester. but i can find the product XC7K100T at Xilinx homepage.
Where can i find it??

**Comment by pkatarzynski** [comment]
Hi jihoon-you 

The correct part number for the FPGA used in the project in is XC7K160T-FFG676. This is mentioned in the the KiCAD design files and can be generated into a BOM list. We have used a XC7K160T-2FBG676C version for prototyping.

So, the FPGA part number mentioned in README  was incorrect. I have fixed that. Thanks for spotting this.
